[package]
name = "std140"
version = "0.1.0"
authors = ["RSSchermer <roland0507@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
std140-macros = { version = "0.1.0", path = "../std140_macros" }
